### ISSUE TITLE
Compilation on Ubuntu16.04 fails: Package JSCORE does not exist

### ISSUE THREAD

**Issue by xsteve** [next-browser/next#104]
# make build-gtk 
sbcl --load next.asd \
        --eval '(ql:quickload :next/gtk)' \
        --eval '(asdf:make :next/gtk)' \
        --eval '(quit)'
This is SBCL 1.3.1.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "next/gtk":
  Load 1 ASDF system:
    next/gtk
; Loading "next/gtk"
......................................; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Package JSCORE does not exist.
;   
;       Line: 215, Column: 54, File-Position: 8421
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM
;                 for "file /home/stefan/work/git/next/next/source/gtk/gtk.lisp"
;                 {1007E70B03}>

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {100399CAD3}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "next/gtk" "gtk/gtk">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "next/gtk" "gtk/gtk">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "next/gtk" "gtk/gtk">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "next/gtk"
  5: [CONTINUE                     ] Ignore runtime option --eval "(ql:quickload :next/gtk)".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "next/gtk" "gtk/gtk">)))

**Comment by jmercouris** [comment]
Hi, thank you for your report! Did you make sure to install cl-webkit from the repository here: https://github.com/next-browser/cl-webkit ?

**Comment by xsteve** [comment]
stefan@sandburg ~/work/git% git clone https://github.com/next-browser/cl-webkit                                                                                                                                                                                                 
Klone nach 'cl-webkit' ...
remote: Counting objects: 1507, done.
remote: Total 1507 (delta 0), reused 0 (delta 0), pack-reused 1507
Empfange Objekte: 100% (1507/1507), 218.14 KiB | 328.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (1001/1001), Fertig.
Prüfe Konnektivität ... Fertig.
stefan@sandburg ~/work/git% cd cl-webkit                                                                                                                                                                                                                                        22:18
stefan@sandburg (git)-[master]- work/git/cl-webkit% l                                                                                                                                                                                                                           22:18
insgesamt 32
drwxrwxr-x  4 stefan stefan 4096 Jun 12 22:18 ./
drwxrwxr-x 16 stefan stefan 4096 Jun 12 22:18 ../
-rw-rw-r--  1 stefan stefan   79 Jun 12 22:18 CONTRIBUTORS
-rw-rw-r--  1 stefan stefan 1066 Jun 12 22:18 COPYING
drwxrwxr-x  8 stefan stefan 4096 Jun 12 22:18 .git/
-rw-rw-r--  1 stefan stefan   32 Jun 12 22:18 .gitignore
-rw-rw-r--  1 stefan stefan 1884 Jun 12 22:18 README.org
drwxrwxr-x  2 stefan stefan 4096 Jun 12 22:18 webkit2/
stefan@sandburg (git)-[master]- work/git/cl-webkit% sbcl                                                                                                                                                                                                                        22:18
This is SBCL 1.3.1.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :cl-webkit2)
To load "cl-webkit2":
  Load 1 ASDF system:
    cl-webkit2
; Loading "cl-webkit2"
...........................
(:CL-WEBKIT2)
* %                                                                      

I hadn't installed it. So I did it - see above

However building next fails with the same error message as above....

**Comment by jmercouris** [comment]
Ja aber das hier ist der problem: https://github.com/next-browser/cl-webkit#installation

did you clone it to the directory specified? You have to make sure that it is not loading cl-webkit2 from quicklisp remote sources, and that is using the version from the repository. Unless `~/work/git` happens to be within your ASDF search path. For example, within my own configuration see here:

https://github.com/jmercouris/configuration/blob/master/.config/common-lisp/source-registry.conf.d/user-lisp.conf

you may also find more information here from the asdf manual:
https://common-lisp.net/project/asdf/asdf.html#Configuring-ASDF-to-find-your-systems

**Comment by xsteve** [comment]
Thanks! Cloning to ~/common-lisp/quicklisp/local-projects/cl-webkit helped.

I have now a working next-gtk binary

But I won't get very happy with it. The browser crashes after a few minutes.
Is there a way to find out why it crashes?
Should I report these crashes in a new issue?

**Comment by vindarel** [comment]
FYI there's an issue discussing crashes: https://github.com/next-browser/next/issues/97

**Comment by jmercouris** [comment]
Yes unfortunately, I don't use GTK, so I have no idea why it crashes. I'm on MacOS, so it is not so easy for me to test. In a VM it seems to work OK for me. Anyways, we can keep it in the other thread for now!
