### ISSUE TITLE
Error: Unbound variable: CCL::COMMAND-LINE-ARGUMENTS

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [next-browser/next#106]
Building from source on Mac OS X High Sierra, I get the following when I run from the command line in the Next.app folder:
```
❯ ./next 
> Error: Unbound variable: CCL::COMMAND-LINE-ARGUMENTS
> While executing: UNIX-OPTS:ARGV, in process Initial(0).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options
```

I get the nEXT app bobbing up and down but never launching and have the CCL command line open in the terminal. 

This has happened for the last month or so compiling from Master.

**Comment by jmercouris** [comment]
Yes it does seem like a unix-opts bug. Maybe we should put a CCL directive so that it can compile on OSX,

-John

**Comment by vindarel** [comment]
This seems fixed on unix-opts 0.1.7, published in late april of this year (see the answer on the issue above). What version are you using ?

**Comment by tinder-jonathanwilner** [comment]
I'm using what's bundled with nEXT. I'll take a look at figuring out how to grab 0.1.7 and replace the bundled version. Thanks!

**Comment by jmercouris** [comment]
it's not what it is bundled with nEXT, it is what is on the quicklisp dist your computer is versioned on. I'm not sure what version is on latest, but on my machine it is at:

` ~/.quicklisp/dists/quicklisp/software/unix-opts-20180131-git:`

so January 31, 2018

**Comment by tinder-jonathanwilner** [comment]
Fixed by updating QuickLisp to the latest QuickLisp dist.
