### ISSUE TITLE
Cannot use nEXT 0.04 binary release

### ISSUE THREAD

**Issue by anhluong156** [nEXT-Browser/nEXT#13]
Whenever I try to open the app, nothing shows.

**Comment by jmercouris** [comment]
The binary? What happens? Can you please try launching it from a terminal and posting the output?  
`nEXT.app/Contents/MacOS/nEXT`

**Comment by sethaldini** [comment]
I'm having the same issue.

> Error: Can't create directory "/Users/jmercouris/".
> While executing: ENSURE-DIRECTORIES-EXIST, in process Initial(0).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.

**Comment by jmercouris** [comment]
Hi, thank you both for your report, I think I have an idea of what is happening. During the creation of my image it seems to be persisting that directory. I will try and see if I can fix it and report back. Thank you for your patience!

**Comment by jmercouris** [comment]
@sethaldini @anhluong156 

Hi, thank you both for your report, the mistake has been fixed, please see commit: https://github.com/nEXT-Browser/nEXT/commit/9e17bbe2659ff97dfdb1f6af0704089b31aea14d

Please re-download and try running again, and please any feedback and suggestions are greatly appreciated, feel free to open issues with feature suggestions. Thank you once again!

**Comment by anhluong156** [comment]
great. Thanks!
