### ISSUE TITLE
GTK Port for nEXT

### ISSUE THREAD

**Issue by ahungry** [nEXT-Browser/nEXT#14]
Attempting to load via Quicklisp on a GNU/Linux machine failed as follows:

```lisp
[package sqlite]......................
> Error: Module cocoa was not provided by any function on *MODULE-PROVIDER-FUNCTIONS*.
> While executing: REQUIRE, in process listener(1).
```

Is nEXT an OSX only browser?

**Comment by jmercouris** [comment]
Hi @ahungry 

nEXT is NOT an OSX only browser. It is designed to be a cross-platform browser. The original implementation was with QT, but due to performance reasons QT has been dropped in favor of GTK. This leaves nEXT in a state of flux as the QT support has been dropped, but the GTK support has not been completed.


I'm currently looking for someone to help work on the GTK port. If you are interested, any help would be appreciated, thank you!

**Comment by ahungry** [comment]
Thanks - have you looked into/considered something like https://github.com/yue/yue ? I used it recently on a c++ project, it worked quite well.

Granted, we would need to implement CL bindings for the lib via a cffi/uffi (I don't think any exist yet) but the lib is very nice and could be a strong contender for native cross platform GUI projects with a uniform API

**Comment by jmercouris** [comment]
That is a very interesting idea you have. When I was originally using QT, the idea of course was to have it be cross platform. Unfortunately, as you know, QT widgets have performance drawbacks next to native. Looking at this system I assume it does some kind of "native" usage of widgets and just wraps them in some abstraction?

Given this, is it possible to use a native web-view with yue? If not, we'll have to stick to native. You'll see that the cocoa-wrapper is actually a very small amount of code. The Lisp GTK work should be relatively easy as well, I just have not started it as I have no experience with GTK.

**Comment by ahungry** [comment]
It does have a WebView class, although I haven't tried it out yet.  If the OS specific display level code is minimal in nEXT, it may not be worth the additional dependency/abstraction however.

**Comment by jmercouris** [comment]
Yeah, it is pretty minimal, so probably not worth the extra effort. Have you ever worked with the GTK stuff? Would you be willing to work on it?

**Comment by ahungry** [comment]
Sure, I'll take a peek and see if I can cobble anything useful together

**Comment by ahungry** [comment]
I think with smart read-time conditionals, this could be usable on SBCL+GTK, as almost all the CCL specific calls are only there for integration with cocoa/macOS things.

**Comment by jmercouris** [comment]
That's correct about the CCL specific calls. I would like to avoid implementation specific calls altogether actually, so that it could just work with CCL on both platforms, and with any implementation on Linux. It is my understanding that the wrappers for GTK on Linux support most implementations already. A good starting point for how to do some of the GTK stuff may be here at an older project: https://github.com/AeroNotix/lispkit.

Additionally, if you have suggestions about how to redo the interface classes, I am all ears. I was personally thinking about removing the "interface" package and just having the Application be a CLOS object. I think the Interface package idea appealed to me due to my past life as a Java developer, but the more I think about it, I don't think it adds any value to the project.

**Comment by deadtrickster** [comment]
Hi, will gtk happen soon?

**Comment by jmercouris** [comment]
Hi! Yes! You can see my very rudimentary progress on the GTK branch, I can draw a window and do some small button things, I’m definitely working on it. One thing that can use some work is the cl webkit bindings provided by Joachim, Ive spoken with him and it is something we will work on soon! Sorry for the delay! I will keep you updated!

**Comment by jmercouris** [comment]
In terms of timeframe, I believe an alpha release of GTK can happen within a weeks time :knock on wood:

**Comment by spiderbit** [comment]
I tried to run it in nixos and now even in a docker image over ssh-X passthrough. I am no zClosure or quicklisp user (outside of that) so I was not shure what the problems was. I assume its that even when I think I fail earlier with messages like that:

> Error: Foreign function not found: X86-LINUX64::|object_getClass|

or 

> Error: The value :DEFAULTS is not of the expected type (OR STRING PATHNAME STREAM).

or

> Error: The value :DEFAULTS is not of the expected type (OR STRING PATHNAME STREAM).
> While executing: PATHNAME-HOST, in process listener(1).

even I exactly did follow your Readme, the question is would it be hard to distribute it with a docker image or something like that :D you would support all linux distros with one package.

your docker file would like something like

from fedora (or ubuntu or whatever)
RUN step 1 to setup/build your app
RUN step n ...
CMD ["/path/to/your/app"]

well just focus at the code first but its a pretty hard thing to install, no linux users want to install stuff into /usr/local/ anymore usually we have package managers for that and can't remember when I had to install something manually especialy a interpreter / repl.

**Comment by jmercouris** [comment]
Hello everyone, closing this issue as the experimental GTK release has been pushed to master!!!

**Comment by Thaodan** [comment]
>That is a very interesting idea you have. When I was  originally using QT, the idea of course was to have >it be cross  platform. Unfortunately, as you know, QT widgets have performance  drawbacks next to >native. Looking at this system I assume it does some  kind of "native" usage of widgets and just wraps >them in some  abstraction?
Is this only an issue on OS X?
At least on Linux GTK is not always native and has issues when not using GNOME.

**Comment by jmercouris** [comment]
Hi, yes this is an issue only on OSX, but only kind of.


1. qt is a much more “complete” port, and the qt team prefers webengine over webkit

2. usage of a reasonably new version of qt required ecl which was a little challenging to produce standalone binaries

3. a qt port may be possible in the reasonable future using something like clasp which has great c++ interop

so as you can see, there were a lot of things to consider :D

at the very least the new architecture gives great flexibility when porting to new systems, theoretically any new port only needs to support the following

1. ability to perform ipc via some means (socket, shared memory etc)

2. a port of a web engine of sorts that can render

3. support for basic gui manipulation (eg show a table view, etc)

**Comment by Thaodan** [comment]
1. They do but there's an project to use an more updated WebKit version or put in in an other term to update Qt-webkit.

It's just that with Qt more stuff is platform independent and runs everywhere. This is why for example things like cantata runs on Windows without any real work except the installer.

Am 27. Januar 2018 09:33:37 MEZ schrieb John Mercouris <notifications@github.com>:
>Hi, yes this is an issue only on OSX, but only kind of.
>
>
>1. qt is a much more “complete” port, and the qt team prefers webengine
>over webkit
>
>2. usage of a reasonably new version of qt required ecl which was a
>little challenging to produce standalone binaries
>
>3. a qt port may be possible in the reasonable future using something
>like clasp which has great c++ interop
>
>so as you can see, there were a lot of things to consider :D
>
>at the very least the new architecture gives great flexibility when
>porting to new systems, theoretically any new port only needs to
>support the following
>
>1. ability to perform ipc via some means (socket, shared memory etc)
>
>2. a port of a web engine of sorts that can render
>
>3. support for basic gui manipulation (eg show a table view, etc)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/next-browser/next/issues/14#issuecomment-360969854

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by jmercouris** [comment]
1. I'm aware of that project, it's not exactly easy to get setup with. It's a huge burden on contributors to setup a QT environment, believe me, I've been down that path, I didn't rewrite everything for fun :D

QT might be more platform independent, but I'm okay with that, as I believe in being as "native" as possible, that's why I prefer things like Xamarin to QT. Hence my current approach.

**Comment by Thaodan** [comment]
1. As is every environment without as package manager :D 

How is Xamarin/GTK native? Even on Linux is neither of them "native".
