### ISSUE TITLE
Bookmark keybindings

### ISSUE THREAD

**Issue by anhluong156** [nEXT-Browser/nEXT#16]
S-s k: Delete Bookmark
    S-s o: Open Bookmark
    S-s s: Bookmark Current Page

Hi,

According to your user manual, the special key is the command key on macs, but when I try using the command key for the above commands, I cannot use the bookmark function at all.  I have tried the other keys as well. Can you please let me know how to use this function as I really need it.

**Comment by jmercouris** [comment]
Hi thank you for your feedback! I’m sorry I did not update the documentation, the latest keybindings can be seen here: https://github.com/nEXT-Browser/nEXT/blob/master/next/source/base.lisp


Please feel free to submit a PR with any documentation suggestions/updates/ or improvements! When I’m back at my desktop I can write out the exact bindings,

Thanks!

**Comment by jmercouris** [comment]
```
S-b s: Save Bookmark

S-b o: Bookmark Open

S-b k: Bookmark Delete
```


Hi, I just looked at the source code and it seems the keys were in fact up to date. To clarify how the bookmark system works.

1. You are visiting a page you'd like to bookmark. You press Command + s, then let go of the keys, then you press "s". Your bookmark is now saved.


2. You wish to visit a bookmark, you type in Command + s, then let go of the keys, then you press "o". The system will prompt you for a bookmark to open.


3. To kill a bookmark you type in Command + s, then let go of the keys, then you press "k". The system will prompt you for a bookmark to kill.

**Comment by anhluong156** [comment]
Hi, yes I have tried pressing Command + s, releasing the keys, then pressing "s", but it doesn't work.  Because when I pressed Command + s, released the keys, and pressed o, no prompt showed for me to select a bookmark to open. The other commands work, but not the bookmark ones.  I use a mac.

**Comment by anhluong156** [comment]
Hi, I just read your code and it turns out that the commands should be S-b s, S-b o, S-b k.  In your user manual, I think you wrote them as S-s s, S-s o, S-s k.  Also in your comment above, you also said pressing Command + s several times.  Just thought you would want to update that. Thanks for your help.

**Comment by jmercouris** [comment]
Ah yes, sorry, I confused the prefix command key, I will update the manual! My apologies, I have trouble sometimes with reading, especially spotting differences between word.

Thank you for your assistance!
