### ISSUE TITLE
Bookmark Links

### ISSUE THREAD

**Issue by anhluong156** [nEXT-Browser/nEXT#17]
Hi again,

When I access a link (call it B) that is listed on another web page (A), and use the command for bookmarking link B, the page that is bookmarked is actually page A, not B.  I would have to find out the URL of link B, and directly go to that link (type in the URL blank) in order to correctly bookmark it. 

Is there any way I can bookmark a page after I access it by clicking on a link listed on a previous page without doing the above? Thanks.

**Comment by jmercouris** [comment]
Hi @anhluong156 

Thank you for the great suggestion! I don't personally use bookmarks myself, so any feedback in this domain is always appreciated.

So there are two possibilities here:

1. I make a function that let's you manually type the bookmark you wish to add
2. I make a function that allows you to set the bookmark from a URL on a page


The next release of nEXT will have some features related to link navigation, I think we can come up with a way to do both of those, I'll add this is as a feature and let you know when I get to it, I'll set it as a TODO for version 0.06.


Thanks!!!

-John

**Comment by anhluong156** [comment]
Great, that sounds good. Thanks! Look forward to version 0.06!
-Anh

**Comment by jmercouris** [comment]
Hi Anh,

I've went ahead and done a basic implementation that is now available on master. Unfortunately, 0.06 is a little bit ways away, but if you compile nEXT yourself, you can access this functionality already. It is now present in the manual as well: https://github.com/nEXT-Browser/nEXT/blob/master/documents/MANUAL.org#bookmarks

Hopefully this works for you!! thank you for your patience!

-John

p.s. I tried uploading a build to this message, but it would not let me (not a supported file type)

**Comment by anhluong156** [comment]
Hi John,

I tried compiling but there's an error message that keeps showing, I am not sure if I did something wrong.  I was able to run it from source using the instruction steps you wrote, but I was not able to compile.

I pasted the error message here:

$ ccl -no-init --load "~/nEXT/next/make.lisp"
> Error: There is no package named "QL" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry finding package with name "QL".
> Type :? for other options.
1 > 

Could you let me know if there's anything I can do so I can compile nEXT? Thank you.

**Comment by jmercouris** [comment]
Hi Anh,

I think I know what is going on, if your installation of quicklisp is not located in ~/.quicklisp the make.lisp script will not work. The make.lisp script should be updated to handle two likely locations of quicklisp (~/quicklisp and ~/.quicklisp)


A quick and easy way to get around that is to remove the -no-init flag

You can see a full description of the problem here: https://github.com/nEXT-Browser/nEXT/issues/25

-John

**Comment by anhluong156** [comment]
Great! I was able to compile. Thanks for your prompt response!

**Comment by jmercouris** [comment]
No problem!
