### ISSUE TITLE
Build issue: No external symbol named "MATCH-RE" in package #<Package "CL-STRING-MATCH">

### ISSUE THREAD

**Issue by analyticd** [nEXT-Browser/nEXT#21]
Hi, 

I have cl-strings installed via quicklisp. Doing ccl64 --no-init --load make.lisp results in a build error:

Read error between positions 250 and 940 in /Users/me/.ghq/github.com/analyticd/nEXT/next/source/completion.lisp.
> Error: Reader error: No external symbol named "MATCH-RE" in package #<Package "CL-STRING-MATCH"> .
> While executing: CCL::%PARSE-TOKEN, in process listener(1).
> Type cmd-/ to continue, cmd-. to abort, cmd-\ for a list of available restarts.
> If continued: Create and use the internal symbol CL-STRING-MATCH::MATCH-RE
> Type :? for other options.

Is there a certain version from source of next or of cl-strings that needs to be used to build on OS X Sierra?

Thanks

**Comment by jmercouris** [comment]
Hi thank you for your report!

It should work with any version of cl-strings, I can't imagine why you are getting this error during compilation. Are you able to load the system normally? What happens when you try loading the system via slime? I think you may first need to load the system via slime to install all the packages

**Comment by analyticd** [comment]
Thanks for responding so quickly.

In slime, if I do:

(require :asdf)
(asdf:load-asd "next.asd")

No errors, but when I do 
(next:start)

I get

There is no package named "NEXT" .
   [Condition of type CCL::NO-SUCH-PACKAGE]

Restarts:
 0: [CONTINUE] Retry finding package with name "NEXT".
 1: [USE-VALUE] Find specified package instead of "NEXT" .
 2: [MAKE-NICKNAME] Make "NEXT" be a nickname for package "COMMON-LISP-USER".
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [*ABORT] Return to SLIME's top level.
 5: [ABORT-BREAK] Reset this thread
 --more--

Backtrace:
  0: (CCL::%PARSE-TOKEN #<STRING-INPUT-STREAM  #x30200138529D> #\n (NIL))
  1: (CCL::%PARSE-EXPRESSION #<STRING-INPUT-STREAM  #x30200138529D> #\n (NIL))
  2: (CCL::%READ-LIST-EXPRESSION #<STRING-INPUT-STREAM  #x3020011EB4DD> (NIL) #\))
  3: (CCL::READ-LIST #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL #\))
  4: (CCL::%PARSE-EXPRESSION #<STRING-INPUT-STREAM  #x3020011EB4DD> #\( NIL)
  5: (CCL::%READ-FORM #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL #<STRING-INPUT-STREAM  #x3020011EB4DD>)
  6: (CCL::READ-INTERNAL #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL)
  7: (READ #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL #<STRING-INPUT-STREAM  #x3020011EB4DD> NIL)

Not informative for debugging. But when I do

(load "./next.asd")

I get

Undefined function :REQUIRE called with arguments ("cocoa") .
   [Condition of type CCL::UNDEFINED-FUNCTION-CALL]

Restarts:
 0: [CONTINUE] Retry applying :REQUIRE to ("cocoa").
 1: [USE-HOMONYM] Apply REQUIRE to ("cocoa") this time.
 2: [USE-VALUE] Apply specified function to ("cocoa") this time.
 3: [STORE-VALUE] Specify a function to use as the definition of :REQUIRE.

However I can successfully do

(require "cocoa")
and 
(require "webkit")

from the slime repl. I did note I haven't seen a (require "cocoa") or (require <anything>) in a depends-on form, nothing wrong with it if you can, just haven't seen it done before.

Any ideas?

**Comment by jmercouris** [comment]
Hi, thank you for your response! That sheds a little bit of light on what is going on! I believe that:

`(require :asdf)`
`(asdf:load-asd "next.asd")`

Should be followed by `(ql:quickload "next")` or `(ql:quickload :next)`

Then after the system is loaded you should be able to do:

`(next:start)`


In the future to make it easier to load systems, in your emacs you can set the following configuration for slime-setup 

https://github.com/jmercouris/configuration/blob/master/.emacs.d/develop/_lisp.el

This will allow you to run M-x slime-load-system

This will then allow you to quickly load any system located within your search path, to set up a custom asdf search path, please see this section of the manual: https://common-lisp.net/project/asdf/asdf.html#Configuring-ASDF

Thanks!!! Please let me know if that works!

**Comment by analyticd** [comment]
Doh, I should have seen that you left (ql:quickload :next) out of the instructions in the readme for developers. Once I did that it got to the same error as when executing the build referenced earlier:

Reader error: No external symbol named "MATCH-RE" in package #<Package "CL-STRING-MATCH"> .
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [CONTINUE] Create and use the internal symbol CL-STRING-MATCH::MATCH-RE

So now they both exhibit the same error. 

Please note, which I failed to mention earlier, that (ql:quickload :cl-strings) failed to fetch cl-strings from quicklisp complaining that that system was not found. Sooo, I got the clone of cl-strings from github as of today and symlinked it into ~/quicklisp/local-projects after which it successfully loaded via quicklisp, but as per your build, failed with the match-re error. I don't know if you were expecting cl-strings to be in the quicklisp "cloud" of libraries or if you perhaps don't have any issue fetching it from there. The readme doesn't mention any need to clone cl-strings locally. Perhaps the latest cl-strings from github api has changed? Apparently.

Hope this helps!

**Comment by jmercouris** [comment]
At the time of my downloading cl-string-match it worked, I tried actually just loading it myself on my own machine.

I've spoken to Xach on IRC, and he says that both cl-string-match and cl-strings are available within quick lisp, so it should have been installed. 

Also, cl-strings is not what is being problematic, cl-string-match is being problematic, maybe match-re is no longer available in cl-string-match, I'll take a look and see if the API has changed, if so, we can probably just change a few things.

Also, per Xach, "`(ql:where-is-system "cl-string-match")` might show something informative"

**Comment by analyticd** [comment]
I got to thinking, hey, I wonder if quicklisp needs to be updated: the client and the distribs. Sure enough. It builds fine now. Soo sorry for wasting your time!

**Comment by jmercouris** [comment]
It’s okay, this kind of stuff happens to me all the time :) 


it was great of you to share in case we encounter this problem again

thanks!
