### ISSUE TITLE
Shortcuts don't work after switching to an existing tab

### ISSUE THREAD

**Issue by Manoj321** [nEXT-Browser/nEXT#22]
First of all this is an awesome project and I love it!

I have the latest version 0.05 and whenever I switch back to gmail/gerrit I can't use the shortcuts which gmail/gerrit supports natively. I have to click somewhere on the page first and then everything works as expected.

**Comment by jmercouris** [comment]
That's interesting, I think I know how to solve it, I just have to have a cleanup function call to set focus to the web-view after the switch-buffer function. Thank you for the report! I also have to create an "application-mode" in addition to "document-mode" which doesn't override any keybindings for usage with things like google docs

**Comment by jmercouris** [comment]
Hi! Thank you for your patience, I've fixed this here: https://github.com/nEXT-Browser/nEXT/commit/f2aa30ffb2499341277a7d75e30619e7cada2769#diff-4c2752ba6016a43a0baaf691b5ea0b21R269

It should finally be working now (if you recompile), the changes will not be available in binary form until the next release.
