### ISSUE TITLE
Blank screen on startup - appears broken to new users?

### ISSUE THREAD

**Issue by jonathanwilner** [nEXT-Browser/nEXT#23]
At least on Mac OS X (High Sierra), there's no default home page/start screen. This leaves a new user thinking startup failed, when in fact, hitting C-l URL RET works perfectly well. 

Would you consider a default home page, either a local file or something online ? This could lead to a superior starting experience. 

Thanks !

**Comment by jmercouris** [comment]
Hi, you're absolutely right, that's a great idea, do you think we could maybe make a VERY lightweight page at this repository: https://github.com/nEXT-Browser/nEXT-Browser.github.io and the set it as the default homepage?

**Comment by jmercouris** [comment]
Hi @jonathanwilner this has now been completed! Please see commit: 23cbb80 (please note, that unless you compile from source, this change will not be visible)

once again, thank you for your suggestion!

@Brendan-Schuetze thank you for your contribution!
