### ISSUE TITLE
C-g not generating link hints

### ISSUE THREAD

**Issue by jonathanwilner** [nEXT-Browser/nEXT#24]
On Mac OS X High Sierra, C-g does not generate link hints on any page - just an audio error chime.

**Comment by jmercouris** [comment]
Hi, thank you for the report!

which keys are you literally pressing? The chime indicates an unrecognized action

**Comment by jonathanwilner** [comment]
Hi- I am hitting Control & G. Either the Apple Control or CapsLock mapped to Control.

**Comment by jmercouris** [comment]
Hi thank you for the update! Did you compile it yourself or download the pre-built binary? What happens when you launch the application from the terminal like this "/Applications/nEXT.app/Contents/MacOS/nEXT"? Does it give any more output?

**Comment by tinder-jonathanwilner** [comment]
I am using chunkwm and skhd.  - good call! However, when I disable them, there's no difference.

Using the prebuilt binary - I failed trying to build from source with something going wrong with QT. 

There's no console output when run from the terminal.

**Comment by jmercouris** [comment]
Hey, thank you for the follow up!

That's really strange that you had some issues with QT, as there is no QT in the project used at all :D

Could you please post the build error? I would like to determine whether it is an issue with building and running on different versions of OSX, or something different altogether

Thank you for your time!

**Comment by tinder-jonathanwilner** [comment]
Hi there - sorry for the bad report re: QT. I meant QL. It was the same as #25 -
https://github.com/nEXT-Browser/nEXT/issues/25 . I followed the workaround and got it compiled. 

Unfortunately, same issue & no more output from running from nEXT.app/Contents/MacOS. 👎

**Comment by jmercouris** [comment]
Hi, I've been thinking about what may be causing this behavior as it works on most people's computers. It must be something tied to configuration somehow. What does your keyboard look like? Are you using the American keyboard layout? Do you have any issues with any other keybindings?  What does the modifier keys section look like on your system?

<img width="780" alt="screen shot 2017-12-06 at 16 35 01" src="https://user-images.githubusercontent.com/1691662/33669695-730da626-daa3-11e7-88f5-d6ddb74f938b.png">

**Comment by seanfarley** [comment]
I'm going to guess all of us have something along the lines of caps lock being mapped to control (I know I do).

**Comment by jonathanwilner** [comment]
This works for me in the latest HEAD.

Layout is US English, caps lock mapped to control.

**Comment by jmercouris** [comment]
I'm glad to hear that it is working now! I'll close this issue then!
