### ISSUE TITLE
honor the XDG directory specification

### ISSUE THREAD

**Issue by jmtd** [nEXT-Browser/nEXT#29]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

so instead of hardcoding `~/.next.d` you'd check for `$XDG_CONFIG_HOME` and if set use `$XDG_CONFIG_HOME/next` (or `next.d`), otherwise default to `~/.config/next` (or `next.d`)

This helps to prevent clutter in ~ for people and also gives a measure of control as to where config, data are kept.

Thanks

**Comment by jmercouris** [comment]
Hi! Thank you for your feature suggestion! That is a great idea! I will look into it! I too am bothered when an application just decides to dump something in a directory of its choosing, I wasn't aware of XDG_CONFIG_HOME, but that's a great feature!

**Comment by jmercouris** [comment]
@lehmacdj Has implemented this! @jmtd sorry about the long wait, thank you for your patience!
