### ISSUE TITLE
Unable to run from source on MacOS High Sierra 

### ISSUE THREAD

**Issue by cswank** [nEXT-Browser/nEXT#35]
Hello, I'm pretty sure I followed the instructions in next/readme.org correctly to install ccl and quicklisp.  However, when I try to start the next browser I get the following error:
```
bash-3.2$ ccl
Clozure Common Lisp Version 1.11.5/v1.11.5  (DarwinX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (lo)
> Error: Undefined function LO called with arguments () .
> While executing: CCL::TOPLEVEL-EVAL, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry applying LO to NIL.
> Type :? for other options.
1 > (require :asdf)
:ASDF
NIL
1 > (asdf:load-asd "next.asd")
#P"/Users/craig/.quicklisp/local-projects/next/next.asd"
1 > (ql:quickload :next)
To load "next":
  Load 1 ASDF system:
    next
; Loading "next"
..................................................
..................................................
..................................................
..................................................
4 > (next:start)
> Error: Unbound variable: GLOBAL-MAP
> While executing: CCL::CHEAP-EVAL-IN-ENVIRONMENT, in process listener(1).
> Type cmd-/ to continue, cmd-. to abort, cmd-\ for a list of available restarts.
> If continued: Retry getting the value of GLOBAL-MAP.
> Type :? for other options.
5 > 
```

The same error appears when I follow the instructions for building the binary and start it from the command line.  Can someone tell me what I'm doing wrong?

EDIT: I truncated the output after running (ql:quickload :next)

**Comment by jmercouris** [comment]
Hi thank you for your report! global-map should be *global-map*, do you have the latest source?

**Comment by jmercouris** [comment]
global-map should have ear-muffs, the github syntax swallowed them in my last comment

**Comment by kageurufu** [comment]
you can type \\\* to escape a character, \*global-map\*

**Comment by cswank** [comment]
Yes, I have the latest master.

**Comment by cswank** [comment]
Aha, I think you meant my init.lisp was incorrect, and you are correct.  I changed to *global-map* in my init.lisp and the build succeeded.  That also explains why my custom keybindings were not working.  Thanks!

**Comment by jmercouris** [comment]
I'm glad everything is sorted out and working!
