### ISSUE TITLE
Command Line Integration

### ISSUE THREAD

**Issue by heywoodlh** [nEXT-Browser/nEXT#45]
Are there any plans/ is it possible to integrate the command line into nEXT? I’ve been using cli tools to supplement my use of nEXT, such as `pass` as my password manager, `buku` as my bookmark manager, and other various tools.

I kind of am just opening this issue as a feature request to be able to run commands from nEXT and to see if that would even be possible. 

Appreciate all the work that has gone into nEXT — it is definitely my daily driver. 👍

**Comment by jmercouris** [comment]
Hey! I'm really glad you are enjoying nEXT! As of now, there are no plans to integrate the command line into nEXT, making a terminal emulator Is really a lot of work. Having said that, I did implement a small example you could put into your init script that would let you run shell commands and see their output.

`C-x s` to start a new shell mode buffer
`c` to enter a new command
`k` to clear the output

this is just a very simple demonstrator, no memory, variables, or anything, something like a Shell is easily possible, especially with inferior-shell (https://gitlab.common-lisp.net/qitab/inferior-shell), but a full Terminal emulator is a lot of work :D

Once again, thank you for interest and opening this issue!

```
(in-package :next)

(defvar *shell-mode-map* (make-hash-table :test 'equalp))

(defclass shell-mode (mode) ())

(defun shell-mode ()
  (make-instance 'application-mode
		 :name "shell-mode"
		 :keymap *shell-mode-map*))

(defparenstatic clear-shell-output
    (setf (ps:chain document body inner-h-t-m-l) ""))

(defparen append-output (output)
  (setf (ps:chain document body inner-h-t-m-l)
        (ps:chain document body inner-h-t-m-l
                  (concat (ps:lisp
                           (concatenate 'string output "<br />"))))))

(defun run-shell-command (input)
  (interface:web-view-execute
   (view *active-buffer*)
   (append-output
    (uiop:run-program input :force-shell t :output :string))))

(defun open-new-shell ()
  (set-visible-active-buffer
   (generate-new-buffer "*shell*" (shell-mode))))

(define-key *shell-mode-map* (kbd "c")
  (:input *minibuffer* run-shell-command))

(define-key *shell-mode-map* (kbd "k")
  #'clear-shell-output)

(define-key *global-map* (kbd "C-x s")
  #'open-new-shell)

```

**Comment by heywoodlh** [comment]
This is exactly what I was looking for. Thank you so much! 

I will try out this code and let you know if I have further questions. If I have issues or questions I will comment on this issue. If it works the way I expect, I will close this issue.

Thanks!

**Comment by heywoodlh** [comment]
So I’m running into issues using this snippet. I am able to open a shell mode buffer, and enter the command. When it runs, nEXT is killed. 

Any suggestions on how to get around this?

**Comment by jmercouris** [comment]
What’s the command you are running? Do any commands work?

**Comment by heywoodlh** [comment]
None of the commands I have tried work. I have tried simple ones like:

`echo ‘hello’`

to using pass:

`pass -c password/path`

None of the ones that I have tried work. As soon as I hit enter, nEXT crashes.

**Comment by jmercouris** [comment]
Can you please post your complete init file? Also, are you running the latest version of nEXT?

**Comment by heywoodlh** [comment]
Yes, absolutely! Here is my ~/.next.d/init.lisp.

I did a pull yesterday and built it from source after your most recent commit yesterday. So I believe I am running the most current version of nEXT.

```
(in-package :next)

(setf *start-page-url* "https://www.the-empire.systems/")

(defvar *shell-mode-map* (make-hash-table :test 'equalp))

(defclass shell-mode (mode) ())

(defun shell-mode ()
  (make-instance 'application-mode
		 :name "shell-mode"
		 :keymap *shell-mode-map*))

(defparenstatic clear-shell-output
    (setf (ps:chain document body inner-h-t-m-l) ""))

(defparen append-output (output)
  (setf (ps:chain document body inner-h-t-m-l)
        (ps:chain document body inner-h-t-m-l
                  (concat (ps:lisp
                           (concatenate 'string output "<br />"))))))

(defun run-shell-command (input)
  (interface:web-view-execute
   (view *active-buffer*)
   (append-output
    (uiop:run-program input :force-shell t :output :string))))

(defun open-new-shell ()
  (set-visible-active-buffer
   (generate-new-buffer "*shell*" (shell-mode))))

(define-key *shell-mode-map* (kbd "c")
  (:input *minibuffer* run-shell-command))

(define-key *shell-mode-map* (kbd "k")
  #'clear-shell-output)

(define-key *global-map* (kbd "C-x s")
  #'open-new-shell)
```

**Comment by jmercouris** [comment]
I tried using your entire init file and everything just worked for me, I first opened a shell-mode buffer

`C-x s`

Then I typed in `c`, then `echo "hello"`, then `RET`

then the output was on screen, https://youtu.be/LlLpBtG9HWc


can you please try launching nEXT from a Terminal like this: `/Applications/./next.app/Contents/MacOS/nEXT` and see if there is any useful output? One thing that may be happening is that uiop is not getting loaded into your image. If so, we could change the uiop:run-program to the CCL specific version

**Comment by heywoodlh** [comment]
Interesting, when I run next from the command line and attempt to execute a shell command using the shell mode buffer, I get this error:

```
> Error: Permission denied : "/var/folders/98/"
> While executing: CREATE-DIRECTORY, in process Cocoa event loop(0).
> Type :POP to abort, :R for a list of available restarts.
```

Which then results in nEXT freezing. 

As a result of that output, I manually created  `/var/folders/98/` and changed the ownership of that folder to my user. That then fixed it and now the shell mode buffer is working properly for me.

As I am not a developer, I would love to know why it creates this folder and what it uses it for? Also, is there any way to fix this behavior in the future?

**Comment by jmercouris** [comment]
Hey, that's very strange, I'm not actually creating that folder, I wonder why CCL is doing that. I'll have to dig into the source code of CCL and figure that out, I'll let you know if I can come up with a good answer

**Comment by jmercouris** [comment]
I'll close this issue for now until I figure it out, thank you for helping me investigate! If on reboot of your machine, the commands no longer work, please re-open this issue, I have some other steps you may try to see what is trying to use this cache.

e.g. typing :R at the prompt and looking at the restarts

**Comment by jmercouris** [comment]
Hi! I believe this issue has been fixed, see the final comment here: https://github.com/next-browser/next/issues/71
