### ISSUE TITLE
Feature Request: Remember scroll position in history

### ISSUE THREAD

**Issue by cjohansson** [nEXT-Browser/nEXT#48]
Thanks for a great application, I love using it to surf the web. 

It would be nice if scrolling positions were saved in history so when you go back in history you will get back to where you were on the page.

**Comment by jmercouris** [comment]
Hi! Thank you very much for the kind words! This is a very good idea, I agree 100%, that is why it is on the roadmap ;)

https://github.com/nEXT-Browser/nEXT/tree/master/next#008

as soon as the Linux port is complete, this will get worked on!

**Comment by cjohansson** [comment]
Sounds great, keep up the good work
