### ISSUE TITLE
gtk version error

### ISSUE THREAD

**Issue by SXGNH** [nEXT-Browser/nEXT#50]
when I'm try run gtk version of nEXT it appear a error:  

> null-pointer in parse-g-param-spec

**the error occur at cl-cffi-gtk/gobject/gobject.param-spec.lisp : line 229**

wm: stumpwm
system: archlinux
library : libwebkit2gtk-4.0.so  , libgobject-2.0.so

slime feedback info :
null-pointer in parse-g-param-spec
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [RETURN-FROM-CALLBACK] #<RESTART GTK::RETURN-FROM-CALLBACK #x7FD483BE356D>
 1: [ABORT-BREAK] Reset this thread
 2: [ABORT] Kill this thread

Backtrace:
  0: (GOBJECT:PARSE-G-PARAM-SPEC #<A Null Foreign Pointer>)
  1: (GOBJECT::CLASS-PROPERTY-INFO #<GTYPE :name "WebKitWebView" :id 140551128687680> "view-mode")
  2: (GOBJECT::CLASS-PROPERTY-TYPE #<GTYPE :name "WebKitWebView" :id 140551128687680> "view-mode" :ASSERT-READABLE T :ASSERT-WRITABLE NIL)
  3: (#<STANDARD-METHOD SLOT-BOUNDP-USING-CLASS (GOBJECT:GOBJECT-CLASS T GOBJECT::GOBJECT-PROPERTY-EFFECTIVE-SLOT-DEFINITION)> #<GOBJECT:GOBJECT-CLASS CL-WEBKIT2:WEBKIT-WEB-VIEW> #<CL-WEBKIT2:WEBKIT-WEB-VI..
  4: (CCL::%SHARED-INITIALIZE #<CL-WEBKIT2:WEBKIT-WEB-VIEW #x30200337F28D> T (:POINTER #<A Foreign Pointer #x7FD4A4204FC0> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT #x302003341B0D>))
  5: (#<CCL::STANDARD-KERNEL-METHOD SHARED-INITIALIZE (STANDARD-OBJECT T)> #<CL-WEBKIT2:WEBKIT-WEB-VIEW #x3020031FC4FD> T :POINTER #<A Foreign Pointer #x7FD4A4204FC0> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTE..
  6: (#<CCL::STANDARD-KERNEL-METHOD INITIALIZE-INSTANCE (STANDARD-OBJECT)> #<CL-WEBKIT2:WEBKIT-WEB-VIEW #x3020031FC4FD> :POINTER #<A Foreign Pointer #x7FD4A4204FC0> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT..
  7: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> (#<STANDARD-METHOD INITIALIZE-INSTANCE #> #<#> #<#> #<#>) ..)) (#<CL-WEBKIT2:WEBKIT-WEB-VI..
  8: (CCL::%CALL-NEXT-METHOD-WITH-ARGS (#(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> (#<#> #<#> #<#> #<#>) (#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> #) ..)))) #<..
  9: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (#(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> (#<#> #<#> #<#> #<#>) ..)))))
 10: (CCL::%CALL-NEXT-METHOD (#(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> (#<#> #<#> #<#> #<#>) (#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> #) ..)))))
 11: (#<STANDARD-METHOD INITIALIZE-INSTANCE :AROUND (GOBJECT:G-OBJECT)> #<CL-WEBKIT2:WEBKIT-WEB-VIEW #x3020031FC4FD>)
 12: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION INITIALIZE-INSTANCE #x30200002CA2F> (#<STANDARD-METHOD INITIALIZE-INSTANCE #> #<#> #<#> #<#>) ..)) 17568840285491 NIL)
 13: (NIL #<Unknown Arguments>)
 14: (CCL::%MAKE-STD-INSTANCE #<GOBJECT:GOBJECT-CLASS CL-WEBKIT2:WEBKIT-WEB-VIEW> (:POINTER #<A Foreign Pointer #x7FD4A4204FC0> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT #x3020031F4B5D>))
 15: (#<CCL::STANDARD-KERNEL-METHOD MAKE-INSTANCE (STANDARD-CLASS)> #<GOBJECT:GOBJECT-CLASS CL-WEBKIT2:WEBKIT-WEB-VIEW> :POINTER #<A Foreign Pointer #x7FD4A4204FC0> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT..
 16: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION MAKE-INSTANCE #x30200002C2AF> (#<STANDARD-METHOD MAKE-INSTANCE #> #<#> #<#>) NIL NIL ..) (#<GOBJECT:GOBJECT-CLASS CL-WEBKIT2:W..
 17: (CCL::%CALL-NEXT-METHOD-WITH-ARGS (#(#<STANDARD-GENERIC-FUNCTION MAKE-INSTANCE #x30200002C2AF> (#<#> #<#> #<#>) NIL NIL (#<#> #<#>)) (#<CCL::STANDARD-KERNEL-METHOD MAKE-INSTANCE (STANDARD-CLASS)>) ..)..
 18: (#<STANDARD-METHOD MAKE-INSTANCE (GOBJECT:GOBJECT-CLASS)> #<GOBJECT:GOBJECT-CLASS CL-WEBKIT2:WEBKIT-WEB-VIEW> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT #x3020031F4B5D>)
 19: (CCL::%%CNM-WITH-ARGS-COMBINED-METHOD-DCODE #(#<STANDARD-GENERIC-FUNCTION MAKE-INSTANCE #x30200002C2AF> (#<STANDARD-METHOD MAKE-INSTANCE #> #<#> #<#>) NIL NIL ..) 17568840285555 NIL)
 20: (NIL #<Unknown Arguments>)
 21: (CCL::%MAKE-INSTANCE #<CLASS-CELL for CL-WEBKIT2:WEBKIT-WEB-VIEW #x302002F8D63D> :CONTEXT #<CL-WEBKIT2:WEBKIT-WEB-CONTEXT #x3020031F4B5D>)
 22: ((:INTERNAL INTERFACE:MAKE-WEB-VIEW))
 23: (LPARALLEL.PROMISE::FULFILL-PROMISE #S(LPARALLEL.PROMISE::%PROMISE :RESULT LPARALLEL.PROMISE::NO-RESULT :LOCK #<RECURSIVE-LOCK "Anonymous lock" [ptr @ #x7FD49C197E00] #x3020031E848D> :CVAR ...) #<COMP..
 24: (CFFI-CALLBACKS::|GTK::CALL-FROM-MAIN-LOOP-CALLBACK| 17568946061638)
 25: (CCL::%PASCAL-FUNCTIONS% 75 17568946061638)
 26: (NIL #<Unknown Arguments>)
 27: (GTK::%GTK-MAIN)
 28: ((:INTERNAL GTK:ENSURE-GTK-MAIN))
 29: ((:INTERNAL BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 30: (CCL::RUN-PROCESS-INITIAL-FORM #<PROCESS cl-cffi-gtk main thread(13) [Active] #x3020031E966D> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL CCL::%PROCESS-RUN-FUNCTION) #x3020031E93FF>))
 31: ((:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (PROCESS))) #<PROCESS cl-cffi-gtk main thread(13) [Active] #x3020031E966D> (#<COMPILED-LEXICAL-CLOSURE (:INTERNAL ..)))
 32: ((:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION))

**Comment by jmercouris** [comment]
Please try with SBCL. I haven't updated the directions yet, but there is a bug in cl-cffi-gtk which presents itself in CCL, but not in SBCL.


So for now, SBCL is far more stable, also, the branch is not quite yet ready :) so expect a few bugs, just working on ironing them out at least a little bit to have a semi-stable alpha

**Comment by jmercouris** [comment]
Please see this issue: https://github.com/crategus/cl-cffi-gtk/pull/56

We may therefore migrate to a version that seems to be more supported: https://github.com/Ferada/cl-cffi-gtk

**Comment by SXGNH** [comment]
sbcl execute **(ql:quickload :next)** report a error:

> invalid directory component: :HOME

but have not error in ccl

sbcl
Backtrace:
  0: (SB-IMPL::UNPARSE-PHYSICAL-DIRECTORY-LIST ("home" "xxxx" ".cache" "common-lisp" "sbcl-1.4.0-linux-x64" :HOME ...) #\\)
      Locals:
        DIRECTORY = ("home" "xxxxx" ".cache" "common-lisp" "sbcl-1.4.0-linux-x64" :HOME ...)
        SB-IMPL::ESCAPE-CHAR = #\\
  1: (SB-IMPL::UNPARSE-UNIX-NAMESTRING #<PATHNAME (with no namestring) :HOST #<SB-IMPL::UNIX-HOST {10000EC033}> :DEVICE NIL :DIRECTORY (:ABSOLUTE "home" "xxxx" ".cache" "common-lisp" "sbcl-1.4.0-linux-x64"..
      Locals:
        PATHNAME = #<PATHNAME (with no namestring) ..>
  2: (NAMESTRING #<PATHNAME (with no namestring) :HOST #<SB-IMPL::UNIX-HOST {10000EC033}> :DEVICE NIL :DIRECTORY (:ABSOLUTE "home" "xxxx" ".cache" "common-lisp" "sbcl-1.4.0-linux-x64" ...) :NAME "package" ..
      Locals:
        PATHNAME = #<PATHNAME (with no namestring) ..>

**Comment by SXGNH** [comment]
I'm glad to help testing,but my engish is not very good ,but I am studying .
I'm very favorite this project.

**Comment by jmercouris** [comment]
Don't worry about your English, it sounds just fine! If you speak Greek, Spanish, or German instead, I can also speak in those if it helps!

I'm not sure exactly what is going on with the pathname in the example above, I have not encountered the same issue in SBCL. Hopefully this can be resolved when I setup xdg_home; https://github.com/nEXT-Browser/nEXT/issues/29
