### ISSUE TITLE
Clicking on link doesn’t add node to history tree

### ISSUE THREAD

**Issue by lehmacdj** [nEXT-Browser/nEXT#54]
Platform: macOS 10.13.2

Steps to reproduce:
1. Go to a webpage (e.g. github.com/next-browser/next)
2. Click on a link using the mouse.
3. Press C-b, one should return to github.com/next-browser/next, but instead one returns to the page before that.

**Comment by jmercouris** [comment]
Hi, thank you for your report!

That's strange, it should work no matter what because events are added to the tree upon the web browser getting a url load request, can you please try to recreate it on something like wikipedia? Maybe it is something to do with JS loading/frameworks

**Comment by lehmacdj** [comment]
[Here is a short gif (15s)](https://imgur.com/a/kPFrv) that illustrates the bug on wikipedia (I had to use imgur because github doesn’t allow uploading .mov files and the converted gif was too large for github). The problem is harder to reproduce on wikipedia but it still occurs with some frequency. In this gif the bug only occurs when clicking on the links “Uganda” for the first time. I am able to return to the article on Vim by pressing C-f. You can then see how on subsequent visits to the “Uganda” article the bug does not occur.




I think the bug is dependent on a race condition involving how soon after loading the page C-b is pressed, because the problem is more prevalent when loading pages that have not been cached. This seems to be a very large problem on github, sometimes even happening after upwards of 30 seconds on pages that were previously cached.

**Comment by jmercouris** [comment]
Hi, thank you for the quick and detailed follow up!

I think I know exactly what the problem is then, you'll see that elements are only added to the history upon the completion of a load: https://github.com/nEXT-Browser/nEXT/blob/master/next/source/cocoa/cocoa.lisp#L103

We could change it to webView:didCommitLoadForFrame: and it would be: "Called when content starts arriving for a page load"

I'm not sure what's better. What do you think?

-John

**Comment by lehmacdj** [comment]
I think that is more similar to what other web browsers use, and would be better.

**Comment by jmercouris** [comment]
I can agree with that, thank you. Would you like to do the PR since you had the honors of discovering this bug :D? If you don't wish to do it, I can also do it a later time, just want to give credit where credit is due!

**Comment by lehmacdj** [comment]
I'll do it
