### ISSUE TITLE
Mac version failing to start

### ISSUE THREAD

**Issue by mofirouz** [next-browser/next#73]
When executing the nEXT browser via Finder on macOS 10.13.3, it simply fails to open.

When I execute the macOS binary from terminal, I get this error:

```
> Error: Permission denied : "/Users/jmercouris/"
> While executing: CREATE-DIRECTORY, in process Initial(0).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

It seems like `jmercouris` user is somehow pre-compiled into the binary which is very wrong.

**Comment by mofirouz** [comment]
Downloaded the latest version from GitHub and the problem seems to be solved.

**Comment by jmercouris** [comment]
I was about to just say, I thought I solved that :D

**Comment by jmercouris** [comment]
At any rate, thank you for filing a report if you think something is Wong! :)
