### ISSUE TITLE
Can’t open tabs etc. in AZERTY

### ISSUE THREAD

**Issue by Haroenv** [next-browser/next#74]
in the AZERTY keyboard, the number keys need to have shift, so the “chirp” error sound will play if you try to type for example ctrl-shift-1, nothing will happen if you type ctrl-1 (which is ctrl-&).

I’m not sure if this is solvable easily

**Comment by jmercouris** [comment]
Hi, thank you for your interest!

I think you may be a little bit confused about the keybindings. To open a new tab you just need to type Ctrl + t

To switch Tabs you can type Ctrl + [ or Ctrl + ]

You can also switch tabs by name with Ctrl + x (let go of keyboard) b

You can find the full manual here: https://github.com/next-browser/next/blob/master/documents/MANUAL.org

**Comment by jmercouris** [comment]
Closing this issue due to lack of update, if you have continue to have problems, please do not hesitate to reopen this issue!
