### ISSUE TITLE
Non-existent file ~/.next.d/bookmark.db

### ISSUE THREAD

**Issue by eadmund** [nEXT-Browser/nEXT#8]
When I attempt to run nEXT for the first time, I get an error:

```
…
[package sqlite]..
; Loading "next"
[package cl-strings]..............................
[package puri]....................................
[package next].
Condition of type: FILE-ERROR
Filesystem error with pathname "~/.next.d/bookmark.db".
Either
 1) the file does not exist, or
 2) we are not allowed to access the file, or
 3) the pathname points to a broken symbolic link.

Available restarts:

1. (TRY-RECOMPILING) Recompile bookmark and try loading it again
2. (RETRY) Retry loading FASL for #<cl-source-file "next" "bookmark">.
3. (ACCEPT) Continue, treating loading FASL for #<cl-source-file "next" "bookmark"> as having been successful.
4. (ABORT) Give up on "next"

Top level in: #<process TOP-LEVEL>.
>
```

It's fixable by running `mkdir ~/.next.d`

**Comment by jmercouris** [comment]
Hi, sorry for the problem! You need to update your home directory with a ~/.next.d folder. This will allow the system to create the bookmarks database, it’s a really new feature and I haven’t yet updated the manual. Please let me know if that works!

**Comment by eadmund** [comment]
It should be possible to ensure that `~/.next.d` exists with `(uiop:ensure-directories-exist #"~/.next.d/")`. I'll work on a PR for this.

**Comment by jmercouris** [comment]
Ok sounds good, I look forward to it :)
