### ISSUE TITLE
WebKit2GTK+ package name on Debian

### ISSUE THREAD

**Issue by lyr3** [next-browser/next#91]
Hy, 

Both Debian and Ubuntu share the same name for the WebKit2GTK+

Debian search: 
```
libwebkit2gtk-4.0-37/unstable,now 2.20.0-2 amd64 [installed,automatic]
  Web content engine library for GTK+

libwebkit2gtk-4.0-37-gtk2/unstable 2.20.0-2 amd64
  Web content engine library for GTK+ - GTK+2 plugin process

libwebkit2gtk-4.0-dev/unstable,now 2.20.0-2 amd64 [installed]
  Web content engine library for GTK+ - development files

libwebkit2gtk-4.0-doc/unstable,unstable 2.20.0-2 all
  Web content engine library for GTK+ - documentation
```

**Comment by jmercouris** [comment]
Hi! Apologies for not replying sooner, I saw this message, but forgot to follow through.

The build system will change dramatically with the next release, and installing these dependencies manually will no longer be necessary. So, thank you for the report, but it is something we won't have to worry about anymore :)

**Comment by lyr3** [comment]
Great...looking forward to it!
