### ISSUE TITLE
INTERFACE:INITIALIZE is undefined

### ISSUE THREAD

**Issue by DJJ88** [next-browser/next#93]
Hello,

I'm on debian 9 and use SBCL. I followed the instructions and tried to [run from source(https://github.com/next-browser/next/tree/master/next#run-from-source)
When I launch (next:start)  I get the following error
The function INTERFACE:INITIALIZE is undefined.
   [Condition of type UNDEFINED-FUNCTION]

**Comment by DJJ88** [comment]
Hello,
Yes, I'm sure about the loading as (ql:quickload :next) execute without any errors.
Thanks for the projects looks promising. 

Best regards,
Jeremie

**Comment by jmercouris** [comment]
Hi Jeremie,

In order to load the GTK frontend, one has to load `(ql:quickload :next/gtk)`

-John

**Comment by DJJ88** [comment]
My apologies I did not understand your instructions.... it loads now. 
thanks again.

Best wishes,
Jeremie

**Comment by jmercouris** [comment]
Hi Jeremie,

no problem :)

please be advised that it is very alpha right now for Linux, and is undergoing a complete rewrite. So don't expect a lot of stability :D

-John
