### ISSUE TITLE
Don't know how to REQUIRE cocoa

### ISSUE THREAD

**Issue by ackerleytng** [next-browser/next#96]
Hi! Quite new to common lisp. 

I'm using sbcl on mac, was following https://github.com/next-browser/next/tree/master/next, and I got this.

```
* (ql:quickload :next/cocoa)
To load "next/cocoa":
  Load 1 ASDF system:
    next/cocoa
; Loading "next/cocoa"

debugger invoked on a SB-INT:EXTENSION-FAILURE in thread
#<THREAD "main thread" RUNNING {10005505B3}>:
  Don't know how to REQUIRE cocoa.
See also:
  The SBCL Manual, Variable *MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     completing load for #<REQUIRE-SYSTEM "cocoa">.
  1: [ACCEPT                       ] Continue, treating
                                     completing load for #<REQUIRE-SYSTEM "cocoa">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "next/cocoa"
  7:                                 Exit debugger, returning to top level.

(REQUIRE "cocoa" NIL)
0]
```

Also, will I have to install cl-webkit and WebKit2GTK+?

Thanks for next, btw!

**Comment by jgkamat** [comment]
Not sure if this is relevant, but the Mac os section says you need ccl, can you try using ccl?

**Comment by jmercouris** [comment]
Hi @ackerleytng , you will have to use CCL. Currently the Cocoa version of of Next depends on CCL's integration with the Cocoa framework via the Objective-C bridge. There is work underway to port similar functionality to SBCL (or rather in an implementation agnostic way, similar to CFFI) (https://github.com/fiddlerwoaroof/objc-lisp-bridge) (primarily in support of McClim), but I would say that it is a long way off.


You can of course just download the binary for now, no need to install CCL if you don't like. Also to note, CCL "installation" is nothing very invasive on a system. You just have to copy a few files into `/opt/..*`

**Comment by ackerleytng** [comment]
Got it! With CCL it works fine. Is there a good place to ask questions about usage? Also, may I contribute to the installation guide?

**Comment by jmercouris** [comment]
Hi, Great!

A good place to ask questions about usage is on the IRC channel: #next-browser which is on Freenode.

The manual can be found here:
https://github.com/next-browser/next/blob/master/documents/MANUAL.org

A document regarding user customizations can be found here:
https://github.com/next-browser/next/blob/master/documents/EXTENSION.org

If you would like to add anything to either of those documents, please feel free to open a pull request!

Thank you for your time and interest!
