### ISSUE TITLE
Commandline argument support?

### ISSUE THREAD

**Issue by Ambrevar** [next-browser/next#99]
I might be missing something, but it seems that `next` does not support commandline arguments at the moment.  That is,

```
next <some-url>
```
fires up Next and opens the start page, not `<some-url>`.

I can provide a patch if required.

**Comment by jmercouris** [comment]
I have only some experience with CLON, I remember having a lot of difficulty. If you are familiar with unix-opts, I wouldn’t mind going with something like that.

**Comment by Ambrevar** [comment]
@vindarel: Would you have time for a pull request soon?  Otherwise I can give it a go.

First thing to support would be URLs as positional argument.  Currently Next is very unpractical as a default browser because it does not open links from external applications.
